spring.application.name=erp-alquimia-do-malte

# Datasource: Supabase (PostgreSQL)
# Connection string provided by user: postgresql://postgres:...@db.jzjskmljmosecjnqtagb.supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://db.jzjskmljmosecjnqtagb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=YKU7ocwvpGNnFHwi
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
