spring.application.name=erp-alquimia-do-malte

# Datasource: Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.jzjskmljmosecjnqtagb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=YKU7ocwvpGNnFHwi
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=YWxxdWltaWFkb21hbHRlc2VjcmV0a2V5Zm9yand0YXV0aFN5c3RlbUVSUDIwMjU=
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs